# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f35f5224fafc87093a57165feb0abf40"
name = "ShopPilot AI"
application_url = "https://shoppilot-ai-inky.vercel.app"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
scopes = "read_orders,read_products,read_customers,read_inventory"

[auth]
redirect_urls = [
  "http://localhost:3000/api/shopify/oauth/callback",
  "https://shoppilot-ai-inky.vercel.app/api/shopify/oauth/callback"
]

[build]
automatically_update_urls_on_dev = true